sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - 7.0

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php

notifications:
  irc:
    channels:
      - "irc.freenode.org#kohana-framework"
    template:
      - "%{repository}/%{branch} (%{commit}) - %{author}: %{message}"
      - "Build details: %{build_url}"
  email: false
